In [1]:
import numpy as np
import pandas as pd

from Sorting_Raw_Frequencies import Sorting_RawFre
from Swarm_Optimize_MagneticVector import Op_MagneticVector

In [2]:
df = pd.read_csv('./Frequencies_CSV_file/fit_fre_B_0.05_Theta_106.0_Phi_157.5.csv')
df2 = pd.read_csv('./Frequencies_CSV_file/fit_fre_B_0.05_Theta_107.7_Phi_158.4.csv')

In [3]:
df

Fitted_frequncies (Hz)  NV_label
0            1.721266e+09         4
1            2.305229e+09         2
2            2.461833e+09         1
3            2.816635e+09         3
4            3.512845e+09         3
5            3.782351e+09         1
6            3.886267e+09         2
7            4.198332e+09         4

In [4]:
df2

Fitted_frequncies (Hz)  NV_label
0            1.882763e+09         4
1            2.813968e+09         2
2            2.919634e+09         1
3            3.412460e+09         3
4            4.098726e+09         3
5            4.299624e+09         1
6            4.325698e+09         2
7            4.376364e+09         4

In [5]:
def Get_SortedFre(df):
    return np.array([df[(df['NV_label'] == uqe)]['Fitted_frequncies (Hz)'].to_numpy() for uqe in np.sort(df['NV_label'].unique())])

In [6]:
fre_sort_byNV = np.array([df[(df['NV_label'] == uqe)]['Fitted_frequncies (Hz)'].to_numpy() for uqe in np.sort(df['NV_label'].unique())])
print(fre_sort_byNV)
print([1, 2, 3, 4])

[[2.4618332e+09 3.7823506e+09]
 [2.3052290e+09 3.8862670e+09]
 [2.8166346e+09 3.5128453e+09]
 [1.7212659e+09 4.1983316e+09]]
[1, 2, 3, 4]


In [7]:
fre_sort_byNV2 = Get_SortedFre(df2)
print(fre_sort_byNV2)

[[2.9196337e+09 4.2996240e+09]
 [2.8139684e+09 4.3256975e+09]
 [3.4124600e+09 4.0987261e+09]
 [1.8827633e+09 4.3763635e+09]]


In [8]:
trans = Sorting_RawFre().Calculate(fre_sort_byNV2[:,0]/1e9, fre_sort_byNV2[:,1]/1e9)
print(trans)

[[[4.299624, 4.3256975, 3.41246, 1.8827633], [2.9196337, 2.8139684, 4.0987261, 4.3763635]], [[2.9196337, 2.8139684, 4.0987261, 4.3763635], [4.299624, 4.3256975, 3.41246, 1.8827633]]]


In [9]:
print(trans[0])

[[4.299624, 4.3256975, 3.41246, 1.8827633], [2.9196337, 2.8139684, 4.0987261, 4.3763635]]


In [10]:
B_result_params_1 = Op_MagneticVector().Calculate(trans[0][0], trans[0][1])
B_result_params_2 = Op_MagneticVector().Calculate(trans[1][0], trans[1][1])

In [12]:
print(B_result_params_1 * 180 /np.pi)
print(B_result_params_2 * 180 /np.pi)

[  2.86479109  72.30012192 -21.60002825]
[  2.86478897 107.69993621 158.40002448]
